/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const User = IDL.Record({ 'id' : IDL.Text, 'nickname' : IDL.Text });
export const Video = IDL.Record({
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'addedBy' : IDL.Text,
  'videoId' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'nickname' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addToQueue' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createRoom' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'userId' : IDL.Text, 'roomCode' : IDL.Text })],
      [],
    ),
  'getConnectedUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(User), 'err' : IDL.Text })],
      ['query'],
    ),
  'getRoomState' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'queue' : IDL.Vec(Video),
            'history' : IDL.Vec(Video),
            'currentVideo' : IDL.Opt(Video),
            'currentTime' : IDL.Float64,
            'isPlaying' : IDL.Bool,
            'users' : IDL.Vec(User),
            'chatHistory' : IDL.Vec(ChatMessage),
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'joinRoom' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'userId' : IDL.Text, 'roomCode' : IDL.Text }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'leaveRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'nextVideo' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'previousVideo' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendChat' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setPlayState' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const User = IDL.Record({ 'id' : IDL.Text, 'nickname' : IDL.Text });
  const Video = IDL.Record({
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'addedBy' : IDL.Text,
    'videoId' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'nickname' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addToQueue' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createRoom' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'userId' : IDL.Text, 'roomCode' : IDL.Text })],
        [],
      ),
    'getConnectedUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(User), 'err' : IDL.Text })],
        ['query'],
      ),
    'getRoomState' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'queue' : IDL.Vec(Video),
              'history' : IDL.Vec(Video),
              'currentVideo' : IDL.Opt(Video),
              'currentTime' : IDL.Float64,
              'isPlaying' : IDL.Bool,
              'users' : IDL.Vec(User),
              'chatHistory' : IDL.Vec(ChatMessage),
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'joinRoom' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'userId' : IDL.Text, 'roomCode' : IDL.Text }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'leaveRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'nextVideo' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'previousVideo' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendChat' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setPlayState' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };