/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'nickname' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface User { 'id' : string, 'nickname' : string }
export interface Video {
  'title' : string,
  'thumbnail' : string,
  'addedBy' : string,
  'videoId' : string,
}
export interface _SERVICE {
  'addToQueue' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createRoom' : ActorMethod<
    [string],
    { 'userId' : string, 'roomCode' : string }
  >,
  'getConnectedUsers' : ActorMethod<
    [string],
    { 'ok' : Array<User> } |
      { 'err' : string }
  >,
  'getRoomState' : ActorMethod<
    [string],
    {
        'ok' : {
          'queue' : Array<Video>,
          'history' : Array<Video>,
          'currentVideo' : [] | [Video],
          'currentTime' : number,
          'isPlaying' : boolean,
          'users' : Array<User>,
          'chatHistory' : Array<ChatMessage>,
        }
      } |
      { 'err' : string }
  >,
  'joinRoom' : ActorMethod<
    [string, string],
    { 'ok' : { 'userId' : string, 'roomCode' : string } } |
      { 'err' : string }
  >,
  'leaveRoom' : ActorMethod<[string, string], undefined>,
  'nextVideo' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'previousVideo' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'sendChat' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setPlayState' : ActorMethod<
    [string, boolean, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];