/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    title: string;
    thumbnail: string;
    addedBy: string;
    videoId: string;
}
export interface ChatMessage {
    nickname: string;
    message: string;
    timestamp: bigint;
}
export interface User {
    id: string;
    nickname: string;
}
export interface backendInterface {
    addToQueue(roomCode: string, userId: string, videoId: string, title: string, thumbnail: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createRoom(nickname: string): Promise<{
        userId: string;
        roomCode: string;
    }>;
    getConnectedUsers(roomCode: string): Promise<{
        __kind__: "ok";
        ok: Array<User>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getRoomState(roomCode: string): Promise<{
        __kind__: "ok";
        ok: {
            queue: Array<Video>;
            history: Array<Video>;
            currentVideo?: Video;
            currentTime: number;
            isPlaying: boolean;
            users: Array<User>;
            chatHistory: Array<ChatMessage>;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    joinRoom(roomCode: string, nickname: string): Promise<{
        __kind__: "ok";
        ok: {
            userId: string;
            roomCode: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    leaveRoom(roomCode: string, userId: string): Promise<void>;
    nextVideo(roomCode: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    previousVideo(roomCode: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendChat(roomCode: string, userId: string, message: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setPlayState(roomCode: string, isPlaying: boolean, currentTime: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { ChatMessage as _ChatMessage, User as _User, Video as _Video } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToQueue(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addToQueue(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToQueue(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRoom(arg0: string): Promise<{
        userId: string;
        roomCode: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0);
            return result;
        }
    }
    async getConnectedUsers(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<User>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnectedUsers(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnectedUsers(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomState(arg0: string): Promise<{
        __kind__: "ok";
        ok: {
            queue: Array<Video>;
            history: Array<Video>;
            currentVideo?: Video;
            currentTime: number;
            isPlaying: boolean;
            users: Array<User>;
            chatHistory: Array<ChatMessage>;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomState(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomState(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinRoom(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            userId: string;
            roomCode: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0, arg1);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0, arg1);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveRoom(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveRoom(arg0, arg1);
            return result;
        }
    }
    async nextVideo(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.nextVideo(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.nextVideo(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async previousVideo(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.previousVideo(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.previousVideo(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendChat(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChat(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChat(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPlayState(arg0: string, arg1: boolean, arg2: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setPlayState(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPlayState(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Video | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    queue: Array<_Video>;
    history: Array<_Video>;
    currentVideo: [] | [_Video];
    currentTime: number;
    isPlaying: boolean;
    users: Array<_User>;
    chatHistory: Array<_ChatMessage>;
}): {
    queue: Array<Video>;
    history: Array<Video>;
    currentVideo?: Video;
    currentTime: number;
    isPlaying: boolean;
    users: Array<User>;
    chatHistory: Array<ChatMessage>;
} {
    return {
        queue: value.queue,
        history: value.history,
        currentVideo: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.currentVideo)),
        currentTime: value.currentTime,
        isPlaying: value.isPlaying,
        users: value.users,
        chatHistory: value.chatHistory
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_User>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<User>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        queue: Array<_Video>;
        history: Array<_Video>;
        currentVideo: [] | [_Video];
        currentTime: number;
        isPlaying: boolean;
        users: Array<_User>;
        chatHistory: Array<_ChatMessage>;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        queue: Array<Video>;
        history: Array<Video>;
        currentVideo?: Video;
        currentTime: number;
        isPlaying: boolean;
        users: Array<User>;
        chatHistory: Array<ChatMessage>;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n4(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        userId: string;
        roomCode: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        userId: string;
        roomCode: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
